INSERT ALL
INTO STUDENT55(STUDENT_ID, NAME, DEPARTMENT, YEAR)
VALUES ('101','SHREYA','IT','2024')
INTO STUDENT55(STUDENT_ID, NAME, DEPARTMENT, YEAR)
VALUES ('102','VAISHALI','CSE','2024')
INTO STUDENT55(STUDENT_ID, NAME, DEPARTMENT, YEAR)
VALUES ('103','SHUBHI','AI','2024')
INTO STUDENT55(STUDENT_ID, NAME, DEPARTMENT, YEAR)
VALUES ('104','SWARNIKA','EC','2024')
SELECT 1 FROM DUAL;

INSERT ALL
INTO COURSES55(COURSE_ID, COURSE_NAME, STUDENT_ID)
VALUES ('01','BTECH','101')
INTO COURSES55(COURSE_ID, COURSE_NAME, STUDENT_ID)
VALUES ('02','BTECH','102')
INTO COURSES55(COURSE_ID, COURSE_NAME, STUDENT_ID)
VALUES ('03','BTECH','103')
INTO COURSES55(COURSE_ID, COURSE_NAME, STUDENT_ID)
VALUES ('04','BTECH','104')
SELECT 1 FROM DUAL;

INSERT ALL
INTO TEACHERS55(TEACHER_ID, TEACHER_NAME, DEPARTMENT)
VALUES ('201','DR RAJIV','IT')
INTO TEACHERS55(TEACHER_ID, TEACHER_NAME, DEPARTMENT)
VALUES ('202','DR PRATIBHA','CSE')
INTO TEACHERS55(TEACHER_ID, TEACHER_NAME, DEPARTMENT)
VALUES ('203','DR POOJA ASOPA','AI')
INTO TEACHERS55(TEACHER_ID, TEACHER_NAME, DEPARTMENT)
VALUES ('204','DR SUPRATIM','EC')
SELECT 1 FROM DUAL;

INSERT ALL
INTO MARKS55(STUDENT_ID, COURSE_ID, TEACHER_ID, MARKS)
VALUES ('101','01','201','90')
INTO MARKS55(STUDENT_ID, COURSE_ID, TEACHER_ID, MARKS)
VALUES ('102','02','202','85')
INTO MARKS55(STUDENT_ID, COURSE_ID, TEACHER_ID, MARKS)
VALUES ('103','03','203','70')
INTO MARKS55(STUDENT_ID, COURSE_ID, TEACHER_ID, MARKS)
VALUES ('104','04','204','55')
SELECT 1 FROM DUAL;







