-- VIEW ALL STUDENTS
SELECT * FROM STUDENT55;
-- VIEW ALL COURSES55
SELECT * FROM COURSES55;
-- VIEW ALL TEACHER55
SELECT * FROM TEACHERS55;
-- VIEW ALL MARKS55
SELECT * FROM MARKS55;

--4- TABLE JOIN (STUDENT + COURSE + TEACHER + MARKS)
SELECT STUDENTS55.NAME,
COURSES55.COURSE_NAME,
TEACHERS55.TEACHER_NAME,
MARKS55.MARKS
FROM MARKS55
JOIN STUDENTS55 ON MARKS55.STUDENT_ID = STUDENTS55.STUDENT_ID
JOIN COURSES55 ON MARKS55.COURSE_ID = COURSES55.COURSE_ID
JOIN TEACHES55 ON MARKS55.TEACHER_ID = TEACHERS55.TEACHER_ID;

--AVERAGE MARKS PER COURSE
SELECT COURSES55.COURSE_NAME, AVG(MARKS55.MARKS) AS AVG_MARKS
FROM MARKS55
JOIN COURSES55 ON MARKS55.COURSES_ID = COURSES55.COURSE_ID
GROUP BY COURSES55.COURSE_NAME;

--STUDENTS TAUGHT BY A SPECIFIC TEACHERS (EXAMPLE: TEACHER_ID = 201)
SELECT STUDENTS55.NAME
FROM MARKS
JOIN STUDENTS55 ON MARKS.STUDENT_ID = STUDENTS55.STUDENTS_ID
WHERE MARKS55.TEACHER_ID = 201;
