CREATE TABLE STUDENT55(
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR (20),
DEPARTMENT VARCHAR (20),
YEAR INT
);

CREATE TABLE COURSES55(
COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR (20),
STUDENT_ID INT,
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT55(STUDENT_ID)
);

CREATE TABLE TEACHERS55(
TEACHER_ID INT PRIMARY KEY,
TEACHER_NAME VARCHAR (20),
DEPARTMENT VARCHAR (20)
);

CREATE TABLE MARKS55(
STUDENT_ID INT,
COURSE_ID INT,
TEACHER_ID INT,
MARKS INT,
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT55 (STUDENT_ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSES55 (COURSE_ID),
FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS55 (TEACHER_ID)
);
